feature/#30 detail view 구현
SOPT-all/35-COLLABORATION-ANDROID-TWOSOMEHEART pull request #32
Opened 2024-11-24 16:38 UTC by kangyein9892

# PR Convention

## ☕ ISSUE
- #30 

## ❗ WORK DESCRIPTION
- detail view 구현을 했습니다.

## 📸 SCREENSHOT

https://github.com/user-attachments/assets/c01b588a-ab07-468d-b2e2-5836c2beb928

## 📢 TO REVIEWERS
- 아직 디자이너님께 탑바에 대한 답변을 못 받앙서

2024-11-24 17:30 UTC, hyeeum requested changes
구현하느라 수고 많으셨어요 :)
코멘트 한 번 천천히 확인하시고 blackbottombutton 스크롤 관련해서 수정해주시면 될 것 같습니당 :)

아래는 실제 투썸하트앱 실행영상입니다

https://github.com/user-attachments/assets/a72be03a-460c-459d-a69c-d45858545a34

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +                )
아직 서버통신 시작을 하지는 않았지만 더미 예시에도 실제 사진의 url을 올리고 이미지를 불러올때도 coil을 사용해보는 것도 좋을 것 같아요 : -)

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +                        .padding(horizontal = 16.dp, vertical = 16.dp)
상하/좌우 모두 동일한 패딩값을 가질때에는 
```suggestion
                        .padding(16.dp)
```
로 설정해주시면 됩니다  :)

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +
공백 지워주세요 !

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailContent.kt
> +    menuPrice: String,
서버에서 price를 어떤 값으로 내려줄까요~! 
추가적으로 core패키지에 있는 PriceFormatter 를 사용해주세요 :)

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +        }
if 를 두 번 사용하신 이유가 있나요?? if-else 로 처리해줘도 될 것 같아요!

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    nutritionWarningTexts: List<String>,
compose와 상태관리..! List는 어떤 성질을 갖고 있어야할까요?
지난 PR 코멘트를 다시 한 번 참고해주세요!

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    val lines = nutritionText.split("\n")
음 저는 이러한 부분도 로직에 포함이 되어야한다고 생각해서 뷰모델에 담는 편인데 예인님은 어떻게 생각하시나요??

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    }
요기 뭐애요??

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +}
만약 아이콘에 클릭이벤트를 주고 싶으신거라면
간단하게 Icon 컴포저블에 modifier로 noRippleClick만 추가해주면 될 것 같아요 :)

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/res/drawable/img_detail_banana_latte.png
나중에는 지워주긔~!

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/res/values/strings.xml
> +    <string name="menu_detail_price_won">원</string>
common에 있는 won 을 사용해주세요 :) !

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailContent.kt
> +                .fillMaxHeight(),
이 부분 fillMaxHeight를 주신 이유가 궁금해요!

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
피그마에 여러 경우가 있어서 혼동이 있는 것 같은데..! 주문하기 버튼은 하단에 고정되어야하는 것 같아요
short는 기본 화면 - long은 스크롤 화면을 표시한 것 같습니다

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +}
text 에 start padding/ icon 에 end padding을 주는 방법도 있고
row 자체에 horizontal padding을 주는 방법도 있을 것 같아요
혹시 따로따로 패딩을 주신 이유가 있나요??

2024-11-24 17:30 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +        viewModel.getDetailDummy()
viewModel::getDetailDummy 으로 접근할 수도 있어요 :)

2024-11-24 17:34 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +                )
실제 사진의 이미지를 피그마 이미지 url으로 불러오면 될까요...!? 아직 url이 안보여서 적용은 못했어요...!!

2024-11-24 17:34 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +                        .padding(horizontal = 16.dp, vertical = 16.dp)
이 부분은 놓쳤네요 감사합니다 !!

2024-11-24 17:37 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +                )
엄 아니면 이번 PR에서 업로드하신 PNG파일 주소로 접근하는 방법도 있겠네요 ~~!

2024-11-24 17:39 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailContent.kt
> +    menuPrice: String,
서버에서 int로 내려주더라고요! priceFormatter의 존재를 까먹고 있었네요...! 감사합니다 ㅎㅎ

2024-11-24 17:41 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +
꼼꼼함 감사합니다 ㅎㅎ

2024-11-24 17:42 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +        }
각각 따로 컴포넌트를 사용하다보니 놓친것 같네요...ㅠㅠ 감사합니다

2024-11-24 17:52 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    nutritionWarningTexts: List<String>,
persistentList 사용해야할 것 같네요....!! ㅠㅠ 그 외에 혹시 상태관리 더 있었나요...!?

2024-11-24 17:59 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    }
이거 바꾸면서 아예 지웠어야했느데 제가 까먹었나봐요 아예 필요 없는 컴포저블인데...!! 수정하겠습니다...!!

2024-11-24 18:01 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +}
안그래도 이미 그렇게 했는데... 컴포저블 안쓰는 거라 삭제했어요 ! 감사합니다!

2024-11-24 18:02 UTC, kangyein9892 commented on app/src/main/res/drawable/img_detail_banana_latte.png
넵 ! 그럼요 😊

2024-11-24 18:05 UTC, kangyein9892 commented on app/src/main/res/values/strings.xml
> +    <string name="menu_detail_price_won">원</string>
common에 있는 won을 못봤네요 ! 감사합니다 !

2024-11-24 18:13 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +        viewModel.getDetailDummy()
엇 혹시 이렇게하면 함수 참조라고 뜨는데... !! 맞을까요?
<img width="407" alt="스크린샷 2024-11-25 오전 3 13 25" src="https://github.com/user-attachments/assets/34f6b019-6549-4afe-8154-5de59ec2c714">

2024-11-24 18:19 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailContent.kt
> +                .fillMaxHeight(),
엇 이유가 없네요...  삭제하겠습니다...!

2024-11-24 18:27 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +}
따로따로 패딩을 준 이유는 없어요 ...! 생각을 제가 못했네요 감사합니다 !

2024-11-24 18:54 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
엇 그러네요 확인했습니다! 그래서 우선 topabar랑 버튼 다 고정해놨습니다 !

2024-11-24 19:24 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    val lines = nutritionText.split("\n")
저도 동의합니다! 뷰에 처리할 로직은 아니니깐요...!! 원래 수정해서 올리려고 했는데 놓쳤네요 감사합ㄴ디ㅏ ㅎㅎ

2024-11-24 19:31 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +                )
pr에 png 올려서 진행해봤어요 감사합니다 ~

2024-11-25 06:41 UTC, hyeeum reviewed
추가적으로 궁금한 점 적었는데 확인해주세요 : -)

2024-11-25 06:41 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +        viewModel.getDetailDummy()
아악 여기서는 안되는ㄴ구나 저의 무식 이슈

2024-11-25 06:41 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
Scaffold 로 변경하신 이유가 있나요?

2024-11-25 06:41 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    nutritionTexts: List<String>?,
null의 경우는 왜 만드셨는지 궁금합니다 :) !

2024-11-25 07:57 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +        viewModel.getDetailDummy()
아마 람다에서 참조 가능할 건데 저도 잘 ...

2024-11-25 07:58 UTC, kangyein9892 commented
> 추가적으로 궁금한 점 적었는데 확인해주세요 : -) 그리구 PR영상도 업데이트해주시면 감사하겠습니닷 히히

집 가서 바로 업데이트 하겠습니다!

2024-11-25 07:58 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    nutritionTexts: List<String>?,
제품 영양 정보의 경우 서버에서 required가 아니여서 만들었습니다!

2024-11-25 08:00 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
제일 밖이 box column 안에 다른 것들 넣고 그 밖에 (column 밖, 박스 안)에 버튼을 넣으면 spacer로 공백을 줘도 겹치더라고요...! 그래서 차라리 scaffold를 써서 상단 하단을 고정시키면 겹치지 않아서 이렇게 진행했습니다...!

2024-11-25 08:56 UTC, sayyyho approved these changes
디테일 뷰 완전 이쁘게 잘 구현하셨네용!! 고생하셨습니다!

2024-11-25 08:56 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +                    )
비동기 이미지를 이렇게 처리하셨구나!! 저도 서버통신 연동 할 때, 도입할게요!

2024-11-25 08:56 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailViewModel.kt
> +        menuImageUrl = "https://private-user-images.githubusercontent.com/69308068/389300533-8d353883-fb4b-4608-b0b4-24d2bc074133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29t
혹시 이 부분은 서버통신을 고려해서 Url로 두신건가요!? 제가 해당 부분 명세를 확인 못해서 궁금해서 여쭤봅니당!!

2024-11-25 10:56 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailViewModel.kt
> +        menuImageUrl = "https://private-user-images.githubusercontent.com/69308068/389300533-8d353883-fb4b-4608-b0b4-24d2bc074133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29t
넵 맞습니다!

2024-11-25 10:56 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
> +                    )
기갓리의 코드를 가져왓습니다 하하

2024-11-25 12:44 UTC, hyeeum approved these changes
수고하셨습니다 :) 
제가 리스트 사냥꾼이라서 해당 부분 한 번 확인해주시고 바로 병합해주시면 될 것 같아요 !! 최고최고 고생하셨어요

2024-11-25 12:44 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailViewModel.kt
> +    private fun splitNutritionText(nutritionTexts: String): List<String>? {
list 사냥꾼

2024-11-25 12:44 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    nutritionText: List<String>?,
list 사냥꾼

2024-11-25 12:44 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    nutritionTexts: List<String>?,
list 사냥꾼

2024-11-25 12:44 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
> +    nutritionTexts: List<String>?,
list 사냥꾼

2024-11-25 12:44 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/DetailModel.kt
> +    val menuNutrition: List<String>?,
list 사냥꾼

2024-11-25 13:27 UTC, kangyein9892 commented
> 수고하셨습니다 :) 제가 리스트 사냥꾼이라서 해당 부분 한 번 확인해주시고 바로 병합해주시면 될 것 같아요 !! 최고최고 고생하셨어요

습관이 무섭네요.... 계속 list만 썼어서... 감사합니다 !

2024-11-25 13:40 UTC, merged