feature/#31 myMenu view 구현
SOPT-all/35-COLLABORATION-ANDROID-TWOSOMEHEART pull request #34
Opened 2024-11-26 08:55 UTC by sayyyho

# PR Convention

## ☕ ISSUE
- #31 

## ❗ WORK DESCRIPTION
- myMenu 뷰를 구현했습니다.

## 📸 SCREENSHOT
<img width="300" alt="image" src="https://github.com/user-attachments/assets/d79809af-6870-4f55-868b-98ba1856b1c0">
<br />
<img width="300" alt="image" src="https://github.com/user-attachments/assets/091732c2-6739-4154-8599-ee83fc64dc4d">

## 📢 TO REVIEWERS
- 기능 구현 부분이 아직 미흡한데, 서버통신 연동하면서 더 수정할게요! 부족한 부분 많이 알려주세요!

2024-11-26 10:28 UTC, hyeeum requested changes
코드정렬 단축키입니당
[Mac OS] Command + Option + L

전체적으로 문자열 추출 및 컴포넌트마다 공백 추가 부탁드려요

아직 피그마하고 대조하면서 확인한게 아니고 코드적인 부분만 확인했어요!
확인하면서 피그마의 레이아웃과 다른 부분이 간혹 보였는데 디자인 한 번 다시 확인부탁드립니당

안드가 처음이라 어려우셨을텐데 ㅠㅠ 구현하시느라 고생하셨고 코멘트도 겹치는 부분이 많으니 너무 두려워하지 마시고 하나하나 읽어보시길 바라요 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +
공백 제거해주세요~!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +    viewModel: MyMenuViewModel
[기본값이 있는 인자가 하단에 위치해야합니다
만약 기본값이 있는 인자가 여러 개일 경우, modifier 가 가장 상단에 위치해야합니다! ](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-component-api-guidelines.md#parameters-order)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +    Box(
컴포넌트마다 띄어쓰기 한 번 넣으면 좋을 듯 해요!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                title = "선택된 상품을 My 투썸에서 삭제할까요?",
스트링 추출 해주세요

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +    viewModel: MyMenuViewModel
뷰모델을 넘겨주는 대신 뷰모델에 있는 함수를 넘겨주어야 해요 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                        text = "전체선택",
스트링 추출 해주세요

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                    text = "선택삭제",
스트링 추출 해주세요

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +            )
strings 파일에 있는 리소스를 사용해 Description을 채워주세요! 
Description을 추가해야하는 이유로 예인님의 코멘트도 추가할게요 ! 

> 음 디스크립션이 있는 이유가 접근성으로 스크린 리더기로 안내를 해주려는 의미에서 있는거다보니 화면을 읽어주는 개념에서 저는 아이콘이 어떤 아이콘이 설명되려면 필요하다고 생각하는 편입니다!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +            place = "삼성역점",
스트링 추출 해주세요

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                        34.dp
어느부분에 padding값을 넣어주는지 이름도 표시해주시면 좋을 것 같아요 :)
추후에 확인할 때 편하실거에요!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                    .width(283.dp)
너비가 큰 기기에서는 해당 모달이 작아보이지 않을까요? 이렇게 큰 값의 경우에는 고정dp를 사용하기보다 기기의 화면크기를 가져와 비율로 설정하는 것을 추천드립니다 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                        .background(color = TwosomeHeartColors.Gray20)
바로 Gray20으로 접근 가능해용

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +            .padding(15.dp, 16.dp)
여기도 위의 코멘트와 마찬가지로 어느 부분에 패딩값을 줬는지 명시해주면 좋을 것 같아요

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +                        text = "${price}원",
요런 애들도 스크링 추출가능함~!!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +    @DrawableRes menuImage: Int,
어노테이션 붙인 거 좋아요~~ ㅋㅋ

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +    onCheckedChange: () -> Unit,
인자 순서 주의~~!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +            modifier = Modifier.clickable { onCheckedChange() }
clickable 말고 noRippleClickable 사용해주세요 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +    @DrawableRes menuImage: Int,
하지만 저희는 이미지를 Int가 아니라 서버에서 String으로 받아오는 것 같은데
 명세확인해주시고 string 이라면 coil을 사용해주세요 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +            )
coil 사용해보기~~!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +                    .border(width = 1.dp, color = Color(0xFF000000))
이 친구는 왜 디자인시스템 컬러 사용을 안하셨나요?!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/res/drawable/img_banana_ameicano2.png
추후에 삭제해주세요 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                )
이 컴포넌트도 클릭 이벤트가 있어야 할 것 같네요 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +
공백 지워주세용

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                            contentColor = Color.Black, // 버튼 텍스트 색상
Color.White 혹시 저희가 정의한 색상 White로 적용이 안되나요?

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                Box(
Box대신 Row만으로도 레이아웃 만들어질 것 같아요~!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +    place: String,
인자 순서 변경해주세요 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +            .background(Color.White)
여기도 우리가 정의한 색상으로 사용합시다 ~!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +                        text = "${price}원",
priceFormatter 에 천원단위로 쉼표 붙여주는 친구를 만들어놓았사오니 사용해주세요 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +                        Text(
여기도 priceFormatter사용해주세요 :)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +                    .border(width = 1.dp, color = Color(0xFF000000))
요기도 컬러 설정해주세용

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/model/MyMenuModel.kt
> +    @DrawableRes val menuImage: Int,
서버에서 Int 값을 내려줄까요 String 값을 내려줄까요~!

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +fun MyBottomSheet(
패키지명이 mymenu 여서 MyMenuBottomSheet 도 괜찮을 것 같네요! (이건 옵셔널입니다~)

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuViewModel.kt
> +    }
이 부분은 저도 한 번 같이 고민해봐야할듯요 난 로직이 제일 어려워

2024-11-26 10:28 UTC, hyeeum commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                    }
추가적으로 이 부분은 코드를 줄이고싶으시다면 Text 하나로도 구현 가능합니다! (옵셔널) 
이거 궁금하시면 내일? 알려드릴게요

2024-11-26 10:30 UTC, hyeeum commented on app/src/main/res/drawable/ic_modal_checkbox_diselect.xml
추가적으로 공통 아이콘은 이미 업로드 해놨습니다 해당 아이콘을 사용해주세요!
ic_checkbox_diselect.xml

2024-11-26 13:23 UTC, kangyein9892 requested changes
대체적으로 혜음님이 잘 얘기해주셔서 제가 얘기할 건 크게 없는 것 같네요...! color랑 stringResource 잘 신경써서 해주시면 좋을 것 같아요 ! contentDescrpition도요!

2024-11-26 13:23 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +    viewModel: MyMenuViewModel
혜음이두 말햇지만
순서가
필수인자(기본값이 없는 인자)
modifier
선택인자(기본값이 있는 인자)
이렇게 쓰면 됩니다 !
(저번주에 카페에서 잠깐 말했던 이야기😊)

2024-11-26 13:23 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                        color = Color.White,
사소한거기는 하지만 Color.White보단 저희가 테마에서 설정한 White로 하면 좋을 것 같아요 !

2024-11-26 13:23 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                    }
혜음님 말 이어서 말하자면 제 MenuCautionChip 참고하시면 좋아요 !

2024-11-26 13:23 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                            contentColor = TwosomeHeartColors.Red40, // 버튼 텍스트 색상
여기도 위에 코멘트 참고해서 수정하면 좋을 것 가가탕요 !

2024-11-26 13:23 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                            .background(color = TwosomeHeartColors.Gray20)
요기 color도...!

2024-11-26 13:23 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +fun MyBottomSheet(
근데 bottomsheet라고 하니까 modal bottom sheet가 생각나서 뭔가 하단 부분이다 라는 네이밍이 더 좋을 것 같아요 !

2024-11-26 13:23 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +                text = "주문하기",
stringResource 잘 부탁드립니다 ~~

2024-11-26 13:23 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +            .background(TwosomeHeartColors.White)
요기 컬러도 확인 부탁드려요 !

2024-11-26 13:23 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +                        contentDescription = "",
contentDescription 잘 사용 해주세요 !!

2024-11-27 05:35 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +
clear

2024-11-27 05:36 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +    viewModel: MyMenuViewModel
clear

2024-11-27 05:39 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +    Box(
clear

2024-11-27 05:50 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                title = "선택된 상품을 My 투썸에서 삭제할까요?",
clear

2024-11-27 06:00 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +    viewModel: MyMenuViewModel
clear - 덕분에 타당한 이유를 알게됐습니다!!

2024-11-27 06:04 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                        text = "전체선택",
clear

2024-11-27 06:04 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                    text = "선택삭제",
clear

2024-11-27 06:06 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +                    .border(width = 1.dp, color = Color(0xFF000000))
clear

2024-11-27 06:10 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +            )
clear

2024-11-27 06:13 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +            place = "삼성역점",
clear

2024-11-27 06:20 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                        34.dp
clear

2024-11-27 06:40 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                    .width(283.dp)
clear

2024-11-27 06:41 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                        .background(color = TwosomeHeartColors.Gray20)
헉... 레전드 첨 알았어요..!!

2024-11-27 06:44 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +            .padding(15.dp, 16.dp)
clear

2024-11-27 07:41 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +    @DrawableRes menuImage: Int,
clear

2024-11-27 07:45 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +    onCheckedChange: () -> Unit,
clear

2024-11-27 07:45 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +            modifier = Modifier.clickable { onCheckedChange() }
clear

2024-11-27 07:45 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +            )
clear

2024-11-27 07:46 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +                    .border(width = 1.dp, color = Color(0xFF000000))
clear

2024-11-27 07:46 UTC, sayyyho commented on app/src/main/res/drawable/img_banana_ameicano2.png
넵!!

2024-11-27 08:15 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                )
우선 API 연결 전이라 noRippleClickable 선언하고 TODO로 두었습니다.

2024-11-27 08:17 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +
clear

2024-11-27 08:17 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                            contentColor = Color.Black, // 버튼 텍스트 색상
clear

2024-11-27 08:24 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                Box(
clear

2024-11-27 08:26 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +    place: String,
clear

2024-11-27 08:26 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +            .background(Color.White)
clear

2024-11-27 08:31 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyBottomSheet.kt
> +                        text = "${price}원",
clear

2024-11-27 08:31 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +                        Text(
clear

2024-11-27 08:36 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/model/MyMenuModel.kt
> +    @DrawableRes val menuImage: Int,
clear

2024-11-27 08:40 UTC, sayyyho commented on app/src/main/res/drawable/ic_modal_checkbox_diselect.xml
clear

2024-11-27 09:03 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                    }
오프라인에서 잘 배웠습니다! 두 분 모두 감사합니다!

2024-11-27 10:21 UTC, kangyein9892 approved these changes
전체적으로 깔끔해진게 보여요 !! 고생하셨어요 !! 지금 코멘트까지만 수정하면 더 좋을 것 같고 시간이 안될 것 같다면 추후에 수정 부탁드려요 !!!

2024-11-27 10:21 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +@SuppressLint("ResourceType")
요거는 왜 추가했는지 알 수 있을까요?! (저는 잘 모르는 친구라 궁금해서 여쭤봐요 !!)

2024-11-27 10:21 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                        contentDescription = "",
contentDescription 한번만 더 잘 부탁드려용...!

2024-11-27 10:21 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                        color = Color.White,
요기 한번 더 체크 부탁드려요....~~

2024-11-27 10:21 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                            contentColor = TwosomeHeartColors.Red40,
요기 color 바로 입력해도 좋을 것 같아요 !

2024-11-27 10:21 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                            text = "확인",
요기 stringResource 사용할까요?

2024-11-27 10:21 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +            contentDescription = "",
요기 ...!!

2024-11-27 10:21 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuBottomSheet.kt
> +                text = "주문하기",
여기도...!!

2024-11-27 10:21 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuBottomSheet.kt
> +                    text = "주문매장",
여기도 체크 부탁드려요 !

2024-11-27 10:21 UTC, kangyein9892 commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuBottomSheet.kt
> +                    text = "주문금액",
여기도 체크 해주세요 !!

2024-11-27 10:26 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +@SuppressLint("ResourceType")
앗 아까 수정하다고 제거를 못했네용! 지우겠습니다!

2024-11-27 10:29 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
> +                        contentDescription = "",
수정했습니다!

2024-11-27 10:31 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                            contentColor = TwosomeHeartColors.Red40,
수정했습니다!

2024-11-27 10:36 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
> +                            text = "확인",
수정했습니다!

2024-11-27 10:37 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
> +            contentDescription = "",
수정했습니다!

2024-11-27 10:39 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuBottomSheet.kt
> +                text = "주문하기",
수정했습니다!

2024-11-27 10:40 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuBottomSheet.kt
> +                    text = "주문매장",
수정했습니다!

2024-11-27 10:41 UTC, sayyyho commented on app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuBottomSheet.kt
> +                    text = "주문금액",
수정했습니다!

2024-11-27 10:51 UTC, hyeeum approved these changes
급한 불부터 끕시다 ㅠㅠ 수고맣았ㄴ어요

2024-11-27 10:53 UTC, merged